# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LetGo < Formula
  desc "Clojure dialect implemented as a bytecode VM in Go"
  homepage "https://github.com/nooga/let-go"
  version "1.13.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nooga/let-go/releases/download/v1.13.0/let-go_1.13.0_darwin_amd64.tar.gz"
      sha256 "3147fbd244bfb127434349fe9309ee48606f61d59fc19fc989879f2fa12d0f05"

      define_method(:install) do
        bin.install "lg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nooga/let-go/releases/download/v1.13.0/let-go_1.13.0_darwin_arm64.tar.gz"
      sha256 "ce25565d703836cb5587ebcbb369e889deb4648211b12e83eafa32f02dd247d0"

      define_method(:install) do
        bin.install "lg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nooga/let-go/releases/download/v1.13.0/let-go_1.13.0_linux_amd64.tar.gz"
      sha256 "c3f5b6e0b7c1236e4dcb44759cfc7c30e1bd39d34a9999422c34673c2feacd78"
      define_method(:install) do
        bin.install "lg"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nooga/let-go/releases/download/v1.13.0/let-go_1.13.0_linux_arm.tar.gz"
      sha256 "17e63840bcc32ab4df74c11f8f7dec8d951cc2e0368964964778dd86f66d1eb1"
      define_method(:install) do
        bin.install "lg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nooga/let-go/releases/download/v1.13.0/let-go_1.13.0_linux_arm64.tar.gz"
      sha256 "96c3284d336ece688bd6ef808182fa8e6811487fe066d5a3dcbe220247970c77"
      define_method(:install) do
        bin.install "lg"
      end
    end
  end
end
