# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LetGo < Formula
  desc "Clojure dialect implemented as a bytecode VM in Go"
  homepage "https://github.com/nooga/let-go"
  version "1.12.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nooga/let-go/releases/download/v1.12.2/let-go_1.12.2_darwin_amd64.tar.gz"
      sha256 "db148bd5b3b0cd2e1dd9a7df277699aa446c9c69aa464844111e38fff93990e5"

      define_method(:install) do
        bin.install "lg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nooga/let-go/releases/download/v1.12.2/let-go_1.12.2_darwin_arm64.tar.gz"
      sha256 "590d7c3469b07ada77ad0ac0628dbd3e224f19d33d9669273cab9082e625cda6"

      define_method(:install) do
        bin.install "lg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nooga/let-go/releases/download/v1.12.2/let-go_1.12.2_linux_amd64.tar.gz"
      sha256 "4a866916f005f044207ecebb6b95ef27d0240d4defc99ddfb8ae1fe8d2e3c077"
      define_method(:install) do
        bin.install "lg"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nooga/let-go/releases/download/v1.12.2/let-go_1.12.2_linux_arm.tar.gz"
      sha256 "132d87b35246cd3f331a82ede8a6ff37a81be8bb93dd2037579a000612b6fbb7"
      define_method(:install) do
        bin.install "lg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nooga/let-go/releases/download/v1.12.2/let-go_1.12.2_linux_arm64.tar.gz"
      sha256 "4fa187c41322991f9cf58f91ccc0638da3d6f87dd392aa3960271361588b581b"
      define_method(:install) do
        bin.install "lg"
      end
    end
  end
end
