# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LetGo < Formula
  desc "Clojure dialect implemented as a bytecode VM in Go"
  homepage "https://github.com/nooga/let-go"
  version "1.12.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nooga/let-go/releases/download/v1.12.1/let-go_1.12.1_darwin_amd64.tar.gz"
      sha256 "2e641522955bf158a49e41535cfcfdf02af05fd0a86a8a2f243dfb1847980b8a"

      define_method(:install) do
        bin.install "lg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nooga/let-go/releases/download/v1.12.1/let-go_1.12.1_darwin_arm64.tar.gz"
      sha256 "fa7f3d0ea96e1a682d9313223cb89b7b1c468184c48de8bccf0092924df291f1"

      define_method(:install) do
        bin.install "lg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nooga/let-go/releases/download/v1.12.1/let-go_1.12.1_linux_amd64.tar.gz"
      sha256 "f2811dc479b42fc38f6bf5f0ee2d089cb8095b9ae1ae097e6de962ac84a2bc1a"
      define_method(:install) do
        bin.install "lg"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/nooga/let-go/releases/download/v1.12.1/let-go_1.12.1_linux_arm.tar.gz"
      sha256 "90901f7a5ba08095a0833af73407337f187f5a16807715638a3ee42cceed88de"
      define_method(:install) do
        bin.install "lg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nooga/let-go/releases/download/v1.12.1/let-go_1.12.1_linux_arm64.tar.gz"
      sha256 "bad077097aa19397cdf90e57ecb4c3d3793fce4e34e9bb85a2dbaaf08e3a0c0d"
      define_method(:install) do
        bin.install "lg"
      end
    end
  end
end
